### ISSUE TITLE
incorrect test

### ISSUE THREAD

**Issue by dgalimi13** [learn-co-curriculum/activerecord-lifecycle-reading#33]
This was a readme. upon running learn i got this error

Failures:

  1) form shows an update form that submits content and redirects and prints out params
     Failure/Error: expect(page).to have_content("My Edit")
       expected to find text "My Edit" in "My Post\nMy post desc"

in the spec it has:
 
describe 'form' do

  it 'shows an update form that submits content and redirects and prints out params' do
    @post = Post.create(title: "My Post", description: "My post desc")

    visit edit_post_path(@post)

    fill_in 'post[title]', with: "My edit"
    fill_in 'post[description]', with: "My post description"

    click_on "Update Post"

    expect(page).to have_content("My Edit")
  end
end

the fill in for "My edit" has lowercase e. i had to alter the test to uppercase to get it to pass

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
