### ISSUE TITLE
unknown error and unable to use rspec or learn. 

### ISSUE THREAD

**Issue by Louiefigz** [learn-co-curriculum/activerecord-lifecycle-reading#7]
This isnt a lab, more like a read along, but i found myself trying to decode this error message with the help of students and instructor Dylan. It seems as though we could not find a solution to what's going on with this error. I can not use learn or rspec or it will raise this error. If someone can help explain why this is going on, that would be helpful since all I did was fork and copy and ran rspec.  I did not change any code except the one line in the model class. 

// ♥ learn 
/Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/abstract_controller/helpers.rb:151:in `rescue in block in modules_for_helpers': Missing helper file helpers//users/aaronfigueroa/development/rails/associations_and_rails/activerecord_lifecycle_reading_v_000/app/helpers/application_helper.rb_helper.rb (AbstractController::Helpers::MissingHelperError)
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/abstract_controller/helpers.rb:148:in `block in modules_for_helpers'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/abstract_controller/helpers.rb:144:in `map!'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/action_controller/metal/helpers.rb:93:in `modules_for_helpers'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/abstract_controller/helpers.rb:108:in `helper'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.5/lib/action_controller/railties/helpers.rb:17:in `inherited'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.5/lib/action_view/test_case.rb:11:in `<class:TestCase>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.5/lib/action_view/test_case.rb:10:in `<module:ActionView>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.5/lib/action_view/test_case.rb:8:in `<top (required)>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-rails-3.4.0/lib/rspec/rails/example/helper_example_group.rb:10:in `<module:HelperExampleGroup>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-rails-3.4.0/lib/rspec/rails/example/helper_example_group.rb:7:in `<module:Rails>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-rails-3.4.0/lib/rspec/rails/example/helper_example_group.rb:4:in `<module:RSpec>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-rails-3.4.0/lib/rspec/rails/example/helper_example_group.rb:3:in `<top (required)>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-rails-3.4.0/lib/rspec/rails/example.rb:4:in `<top (required)>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-rails-3.4.0/lib/rspec/rails.rb:12:in `<top (required)>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/aaronfigueroa/Development/rails/associations_and_rails/activerecord-lifecycle-reading-v-000/spec/rails_helper.rb:7:in `<top (required)>'
	from /Users/aaronfigueroa/Development/rails/associations_and_rails/activerecord-lifecycle-reading-v-000/spec/features/post_spec.rb:1:in `require'
	from /Users/aaronfigueroa/Development/rails/associations_and_rails/activerecord-lifecycle-reading-v-000/spec/features/post_spec.rb:1:in `<top (required)>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `load'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `<main>'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/aaronfigueroa/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by pletcher** [comment]
This might help: http://stackoverflow.com/questions/27871726/strange-error-in-rails-missing-helper

Unfortunately, I've never run into this error myself, and I can't reproduce it. But rest assured that it's probably a Ruby/Rails issue -- there are also some helpful results here: https://www.google.com/search?q=application_helper.rb_helper.rb
